# Generated by Django 4.1 on 2022-09-01 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produto_nome_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
